### ISSUE TITLE
How to add ContainerRequestFilter

### ISSUE THREAD

**Issue by marcocast** [aol/micro-server#31]
Hey guys,

I'd like to add a ContainerRequestFilter to implement some authorization code (similar to this https://simplapi.wordpress.com/2013/01/24/jersey-jax-rs-implements-a-http-basic-auth-decoder/).

Do you know how can I do that using the great microserver lib?

Thanks :)

**Comment by johnmcclean-aol** [comment]
Hi Marco,

Looking at the example, I think you'd want to follow the 'Java built in
server' way. That is register the properties
 "com.sun.jersey.spi.container.ContainerRequestFilters",

"com.sun.jersey.api.container.filter.LoggingFilter;com.myprogram.AuthFilter"

Not sure how simple that is. Two options are too set the DefaultResources
or DefaultJaxRsPackages via ConfigurableModule. Both result in
ResourceConfiguration.register being called rather than property.

Alternatively you could simply add
@Getterprivate static volatile ConcurrentMap<String, List<String>>
propertiesMap = Maps.newConcurrentMap();
To the JerseyRestApplication class and use it to set Properties on the
ResourceConfiguration.

https://github.com/aol/micro-server/blob/master/micro-core/src/main/java/com/aol/micro/server/rest/jersey/JerseyRestApplication.java

In that case, just add the Properties to Module / ConfigurableModule in the
usual way and make sure they get copied across in the
JerseySpringIntegrationContextListener. (It's basically following the exact
same pattern as per Packages or Resources).

https://github.com/aol/micro-server/blob/master/micro-core/src/main/java/com/aol/micro/server/rest/jersey/JerseySpringIntegrationContextListener.java


On Mon, Jul 27, 2015 at 2:26 PM, Marco Castigliego <notifications@github.com

**Comment by marcocast** [comment]
Cool, thanks John.

I think I achieved what I wanted simply creating a spring component that implements javax.servlet.Filter and com.aol.micro.server.auto.discovery.FilterConfiguration.

:) Thanks for the help!

Marco
