### ISSUE TITLE
(Internal Auth app) Integration

### ISSUE THREAD

**Issue by Zeouterlimits** [aol/micro-server#32]
It would be great if it could support bridge across H2K & Spring, or figure some way of solving this issue.

**Comment by johnmcclean-aol** [comment]
Hey guys,

Some thoughts on this. The Functional way to do this would be with an Either Monad, rather than annotations. An Either  can represent one of two states, in this case either Authorised or Not Authorised. We could create a thin wrapper over an Either that makes the intent clear. E.g.

     Authoriser.of(authorisedData)
                     .whenAllowed(this::processData)
                     .whenDisallowd(this::notAuthorisedResponse);

I think it's both clearer and much easier to debug / problem shoot than annotations, as well as being more in fitting with the modern style of programming. Also this might provide some direction for this project as a functional-based REST Microservices library and provide impetus to integrate with Cyclops and simple-react.

td;lr [flatMap that shit](http://www.flatmapthatshit.com/)

**Comment by johnmcclean-aol** [comment]
Hi,

I've added a sample app for this issue, and am able to replicate (registered Binder not being used). 

https://github.com/aol/micro-server/tree/master/micro-core/src/test/java/app/custom/binder/test

This Stackoverflow issue hints that this is an issue with Grizzly and Jersey : http://stackoverflow.com/questions/26527497/jerseytest-running-on-grizzly-does-not-work-with-custom-injection-binders

We could look at migrating to Netty possibly with RestEasy?

Some Jersey / Netty integrations (incomplete)

 https://github.com/Graylog2/jersey-netty/tree/master/src/main/java/org/graylog2/jersey/container/netty

https://github.com/dagingaa/netty-jersey2

RestEasy / Netty might be a better bet, if we consider moving to Netty.
